// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDnLHoVibis8lCN7ucuVQzrUsLJIJpzOQ',
    appId: '1:603019705244:web:fa5f9eeeb816d3c1c52659',
    messagingSenderId: '603019705244',
    projectId: 'kiemtra2351060483',
    authDomain: 'kiemtra2351060483.firebaseapp.com',
    storageBucket: 'kiemtra2351060483.firebasestorage.app',
    measurementId: 'G-YHH42KYF6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZj9p-CGa2n02ALCgQX_kSM6KOWEaFvM',
    appId: '1:603019705244:android:b6f3cacc96a34f93c52659',
    messagingSenderId: '603019705244',
    projectId: 'kiemtra2351060483',
    storageBucket: 'kiemtra2351060483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYHhjhwNLk1epymFn1-NF2mHzl8Tz1IFM',
    appId: '1:603019705244:ios:d7b8b181bf86c827c52659',
    messagingSenderId: '603019705244',
    projectId: 'kiemtra2351060483',
    storageBucket: 'kiemtra2351060483.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2351060483',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYHhjhwNLk1epymFn1-NF2mHzl8Tz1IFM',
    appId: '1:603019705244:ios:d7b8b181bf86c827c52659',
    messagingSenderId: '603019705244',
    projectId: 'kiemtra2351060483',
    storageBucket: 'kiemtra2351060483.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2351060483',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDnLHoVibis8lCN7ucuVQzrUsLJIJpzOQ',
    appId: '1:603019705244:web:f5d7c2ad43ed5415c52659',
    messagingSenderId: '603019705244',
    projectId: 'kiemtra2351060483',
    authDomain: 'kiemtra2351060483.firebaseapp.com',
    storageBucket: 'kiemtra2351060483.firebasestorage.app',
    measurementId: 'G-KG4B9F6V74',
  );
}
